# Generated by Django 5.2.8 on 2025-11-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationItem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationitem',
            options={'verbose_name': 'Reservación', 'verbose_name_plural': 'Reservaciones'},
        ),
        migrations.RemoveField(
            model_name='reservationitem',
            name='created_at',
        ),
        migrations.AddField(
            model_name='reservationitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reservation_images/', verbose_name='Imagen de reservación'),
        ),
        migrations.AddField(
            model_name='reservationitem',
            name='service',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
