# Generated by Django 5.2.8 on 2025-11-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationItem', '0002_alter_reservationitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationitem',
            name='service',
            field=models.CharField(blank=True, max_length=100, verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='reservationitem',
            name='status',
            field=models.CharField(choices=[('open', 'Libre'), ('taken', 'tomada')], default='open', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='reservationitem',
            name='time_end',
            field=models.TimeField(verbose_name='Hora de finalización'),
        ),
        migrations.AlterField(
            model_name='reservationitem',
            name='time_start',
            field=models.TimeField(verbose_name='Hora de inicio'),
        ),
    ]
