# Generated by Django 5.2.8 on 2025-11-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationItem', '0003_alter_reservationitem_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('daily', 'Diariamente'), ('weekly', 'Semanalmente (días específicos)')], max_length=20)),
                ('days_of_week', models.JSONField(blank=True, default=list)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('service', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Reservación recurrente',
                'verbose_name_plural': 'Reservaciones recurrentes',
            },
        ),
    ]
