# Generated by Django 5.2.8 on 2025-11-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationItem', '0004_recurringreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringreservation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reservation_images/', verbose_name='Imagen de reservación'),
        ),
        migrations.AlterField(
            model_name='recurringreservation',
            name='days_of_week',
            field=models.JSONField(blank=True, default=list, verbose_name='Dias de la semana'),
        ),
        migrations.AlterField(
            model_name='recurringreservation',
            name='end_date',
            field=models.DateField(verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='recurringreservation',
            name='rule_type',
            field=models.CharField(choices=[('daily', 'Diariamente'), ('weekly', 'Semanalmente (días específicos)')], max_length=20, verbose_name='Periodicidad'),
        ),
        migrations.AlterField(
            model_name='recurringreservation',
            name='service',
            field=models.CharField(blank=True, max_length=100, verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='recurringreservation',
            name='start_date',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='recurringreservation',
            name='time_end',
            field=models.TimeField(verbose_name='Hora de finalización'),
        ),
        migrations.AlterField(
            model_name='recurringreservation',
            name='time_start',
            field=models.TimeField(verbose_name='Hora de inicio'),
        ),
        migrations.AlterField(
            model_name='reservationitem',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
