# Generated by Django 5.2.8 on 2025-11-18 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationItem', '0005_recurringreservation_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationitem',
            name='recurring_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_items', to='reservationItem.recurringreservation'),
        ),
    ]
