# Generated by Django 5.2.8 on 2025-11-18 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationItem', '0008_alter_reservationitem_recurring_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationitem',
            name='recurring_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_reservations', to='reservationItem.recurringreservation'),
        ),
    ]
