# Generated by Django 5.2.8 on 2025-11-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationItem', '0010_alter_recurringreservation_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationitem',
            name='service',
            field=models.CharField(choices=[('soccer', 'Futbol'), ('tennis', 'Tenis'), ('walley', 'Walley')], max_length=20, verbose_name='Servicio'),
        ),
    ]
