# Generated by Django 5.2.8 on 2025-11-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationItem', '0011_alter_reservationitem_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringreservation',
            name='service',
            field=models.CharField(choices=[('soccer', 'Futbol'), ('tennis', 'Tenis'), ('wally', 'Walley')], max_length=20, verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='reservationitem',
            name='service',
            field=models.CharField(choices=[('Futbol', 'futbol'), ('Tenis', 'tenis'), ('Walley', 'walley')], max_length=20, verbose_name='Servicio'),
        ),
    ]
