# Generated by Django 5.2.8 on 2025-11-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationItem', '0012_alter_recurringreservation_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationitem',
            name='service',
            field=models.CharField(choices=[('soccer', 'Futbol'), ('tennis', 'Tenis'), ('wally', 'Walley')], max_length=20, verbose_name='Servicio'),
        ),
    ]
