# Generated by Django 5.2.8 on 2025-11-26 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_options'),
        ('reservationItem', '0013_alter_reservationitem_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringreservation',
            name='service',
            field=models.CharField(choices=[('Futbol', 'Futbol'), ('Tenis', 'Tenis'), ('Wally', 'Wally')], max_length=20, verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='reservationitem',
            name='service',
            field=models.CharField(choices=[('Futbol', 'Futbol'), ('Tenis', 'Tenis'), ('Wally', 'Wally')], max_length=20, verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='reservationitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='profiles.userprofile', verbose_name='Usuario'),
        ),
    ]
